baseURL: https://legaltech.uliege.be
languageCode: en-us
title: Liège LegalTech Lab
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/legaltech.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Liège LegalTech Lab
    # Hero subtitle (optional)
    subtitle: "de l'Université de Liège"
    # Button text
    buttontext: Présentation
    # Where the main hero button links to
    buttonlink: "/page/presentation"
    # Hero image (from static/images/___)
    image: illustrations/legaltech.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - image: cris-uliege.png
      url: http://labos.ulg.ac.be/cris/
    - image: spiral-uliege.png
      url: http://www.spiral.ulg.ac.be
    - image: openjustice.png
      url: http://openjustice.be
    - image: cite-uliege.png
      url: http://cite.uliege.be
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Accueil
    url: /
  - title: Présentation
    url: '/page/presentation'
  - title: Équipe
    url: '/page/contact'
  # - title:
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  - title: Corpus
    url: https://corpus.lltl.be
    button: true
  section1:
    title: Notre vision
    subtitle:
    tiles:
    - title: Transparence
      icon: mouse-globe
      text: Le LLTL souhaite améliorer la visibilité et l'accessibilité des sources juridiques
      url: /page/vision
      buttonText: Accessibilité
    - title: Développement
      icon: laptop-cloud
      text: Le LLTL développe des outils technologiques sous licence libre à destination des professionnelles de l'analyse juridique textuelle
      url: /page/vision
      buttonText: OpenSource
    - title: Numérique
      icon: plug-cloud
      text: Le LLTL souhaite apporter une réflexion théorique sur les enjeux de la digitalistaion du Droit
      url: /page/vision
      buttonText: Réflexion
  section2:
    title: Programme de recherche
    subtitle: Le Liège Legal Tech Lab (LLTL) a été créé en 2020 à l’interface de deux facultés, la Faculté de Droit et la Faculté des Sciences Sociales de l’ULiege. Le LLTL développe des activités de recherche, de développement et d’innovation en lien avec les technologies et le droit au sein de l’ULiege mais aussi dans le champ du droit belge. Le LLTL est actuellement actif sur trois axes de travail.
    features:
    - title: Axe 1 - R&D
      text: Le **premier axe** consiste à poursuivre le **développement** de l’outil déjà produit en étroite collaboration avec les membres de la Faculté de Droit afin d’enrichir réciproquement leurs pratiques de recherches et les performances de l’outil. Deux années à tiers-temps sont nécessaires pour ce faire.
      icon: doc-sync

    - title: Axe 2 - Diffusion
      text: Le **deuxième axe** consiste à poursuivre les discussions déjà nouées avec des organisations externes à l’ULiege (juridictions et avocature) afin de transposer et adapter à leurs demandes et besoins l’outil développé par le LLTL. Deux années à tiers-temps sont nécessaires pour ce faire.
      icon: laptop-globe

    - title: Axe 3 - Information
      text: Un projet citoyen et politique à travers l’implication de Martin Erpicum et Christophe Dubois dans l’**ASBL openjustice**. Cette plateforme permet d’approfondir nos activités de développement, d’innovation et d’analyse tout en mettant notre expérience au service d’un réseau ouvert et en mouvement.
      icon: doc-sync

  section3:
    title: Une application
    subtitle: Application PoC pour l'analyse des textes juridiques
    image: illustrations/mockups/app-mockup.png
    buttonText: Essayez-la!
    buttonLink: "http://corpus.lltl.be"
  section4:
    title: Notre équipe
    subtitle: Équipe multidisciplinaire
    clients:
    - name: Pierre Delvenne
      quote: Membre fondateur
      job: Chercheur qualifié FNRS, Spiral
      img: pd
    - name: Christophe Dubois
      quote: Directeur
      job: Chargé de cours, CRIS
      img: cd
    - name: Martin Erpicum
      quote: Chercheur
      job: Chercheur & développeur
      img: me

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Suivez-nous
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/tintamarre/corpus/
      # Icons are from Font Awesome
      icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Products"
        links:
        - text: Corpus
          link: https://corpus.lltl.be
        - text: Omdat
          link: https://omdat.openjustice.lltl.be
      column2:
        title: "Contribuer"
        links:
        - text: Comment contribuer
          link: https://github.com/tintamarre/corpus/blob/main/CONTRIBUTING.md
      column3:
        title: "Documentation"
        links:
        - text: Accéder à la documentation
          link: http://docs.lltl.be/
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Carte blanche
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
